#:schema node_modules/wrangler/config-schema.json
name = "openalex-research-mcp"
main = "src/worker.ts"
compatibility_date = "2025-03-17"
compatibility_flags = ["nodejs_compat"]

[vars]
OPENALEX_EMAIL = "valentin.mosor@pm.me"
